version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
  todo:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_NAME: "test"
volumes:
  mongo_db: {}
